//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBaiviet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        [Key]
        public string CommentId { get; set; }

        [Display(Name = "Nội dung")]
        [Required]
        public string Ccontent { get; set; }

        [Display(Name = "Người bình luận")]
        [Required]
        public string UserId { get; set; }

        [Display(Name = "Bài được bình luận")]
        [Required]
        public string PostId { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
